BookChatBot/Bookbot/models.py
from Bookbot import db

class MovieRank(db.Model):
    index = db.Column(db.Integer, primary_key=True)
    title=db.Column(db.String(200),nullable=False)

class ItemBuy(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title=db.Column(db.String(200),nullable=False)
    lprice=db.Column(db.String(200),nullable=False)
    address=db.Column(db.String(200),nullable=False)
    buy_date=db.Column(db.DateTime(),nullable=False)

BookChatBot/Bookbot/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,DateField
from wtforms.validators import DataRequired

class Search_Title(FlaskForm):
    title=StringField('도서명을 입력하세요',validators=[DataRequired()])

class Search_Author(FlaskForm):
    title = StringField('저자명을 입력하세요', validators=[DataRequired()])

class Search_Movie(FlaskForm):
    title=StringField('영화명을 입력하세요',validators=[DataRequired()])

class Search_Rank(FlaskForm):
        keyword = StringField()
        date = DateField()

class Search_Item(FlaskForm):
    title=StringField('제품명을 입력하세요',validators=[DataRequired()])

class Item_Buy(FlaskForm):
    address=StringField('주소',validators=[DataRequired()])

BookChatBot/Bookbot/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData
import config


naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))
migrate=Migrate()

def create_app():
    app=Flask(__name__)
    app.debug=True
    app.config.from_object(config)

    db.init_app(app)
    migrate.init_app(app,db)

    if app.config['SQLALCHEMY_DATABASE_URI'].startswith("sqlite"):
        migrate.init_app(app,db,render_as_batch=True)
    else:
        migrate.init_app(app,db)

    from . import models

    from .views import main_views,author_views,movie_views,shop_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(author_views.bp)
    app.register_blueprint(movie_views.bp)
    app.register_blueprint(shop_views.bp)

    from .filter import Shortword
    app.jinja_env.filters['shortword']=Shortword
    app.jinja_env.filters['datetime'] = Shortword


    return app

BookChatBot/Bookbot/views/author_views.py
from flask import Blueprint , render_template ,request
from Bookbot.forms import Search_Author
from Bookbot.author_api import NaverAuthor
import json

bp = Blueprint('author',__name__,url_prefix='/')


@bp.route('/author', methods=('POST','GET'))
def Authorinfo():
    form = Search_Author()

    if request.method == 'POST' and form.validate_on_submit():
        print(form.title.data)
        result = NaverAuthor(form.title.data)
        result = json.loads(result)
        return render_template('author_info.html',author_info_list = result['items'], form=form)


    return render_template('author_info.html',form=form)

BookChatBot/Bookbot/views/main_views.py
from flask import Blueprint , render_template ,request
from Bookbot.forms import Search_Title
from Bookbot.naverapi import Naverbook
import json

bp = Blueprint('main',__name__,url_prefix='/')



@bp.route('/' , methods=('POST','GET'))
def Bookinfo():
    form = Search_Title()

    if request.method == 'POST' and form.validate_on_submit():
        print(form.title.data)
        result =  Naverbook(form.title.data)
        result = json.loads(result)
        return render_template('book_info.html',book_info_list = result['items'], form=form)



    return render_template('book_info.html',form=form)

BookChatBot/Bookbot/views/movie_views.py
from flask import Blueprint , render_template ,request
from Bookbot.forms import Search_Movie,Search_Rank
from Bookbot.movie_api import NaverMovie
from Bookbot.rank_api import MovieRank
import json
from werkzeug.utils import redirect

bp = Blueprint('movie',__name__,url_prefix='/')


@bp.route('/movie/info' , methods=('POST','GET'))
def Movieinfo():
    form = Search_Movie()

    if request.method == 'POST' and form.validate_on_submit():
        print(form.title.data)
        result =  NaverMovie(form.title.data)
        result = json.loads(result)
        return render_template('movie_info.html',movie_info_list = result['items'], form=form)



    return render_template('movie_info.html',form=form)

@bp.route('/movie/rank' , methods=('POST','GET'))
def Rankinfo():

    if request.method == 'POST':
        form = Search_Rank()
        date=request.form['keyword']
        result = MovieRank(date)
        return render_template('rank_info.html',keyword=date,rank_info_list =result,form=form)
    return render_template('rank_info.html')

BookChatBot/Bookbot/views/rank_views.py
from flask import Blueprint , render_template ,request
from Bookbot.rank_api import MovieRank
from Bookbot.forms import Search_Rank

bp = Blueprint('rank',__name__,url_prefix='/')

@bp.route('/movie/rank' , methods=('POST','GET'))
def Rankinfo():

    if request.method == 'POST':
        form = Search_Rank()
        date=request.form['keyword']
        result = MovieRank(date)
        return render_template('rank_info.html',keyword=date,rank_info_list =result,form=form)
    return render_template('rank_info.html')

BookChatBot/Bookbot/views/shop_views.py
from flask import Blueprint , render_template ,request,url_for
from Bookbot.forms import Search_Item,Item_Buy
from Bookbot.shop_api import NaverShop
from Bookbot import db
from Bookbot.models import ItemBuy
from datetime import datetime
import json

bp = Blueprint('shop',__name__,url_prefix='/')


@bp.route('/shop/info' , methods=('POST','GET'))
def Iteminfo():
    form = Search_Item()

    if request.method == 'POST' and form.validate_on_submit():
        print(form.title.data)
        result =  NaverShop(form.title.data)
        result = json.loads(result)
        return render_template('item_info.html',item_info_list = result['items'], form=form)

    return render_template('item_info.html',form=form)


@bp.route('/shop/buy',methods=['POST'])
def Buy():
    form = Item_Buy()
    stitle=request.form['title']
    slprice=request.form['lprice']

    return render_template('item_buy.html',stitle=stitle,slprice=slprice
                       ,form=form)

@bp.route('/shop/success',methods=['POST'])
def Success():
    title=request.form['title']
    lprice=request.form['price']
    address=request.form['address']

    buy=ItemBuy(title=title,lprice=lprice,address=address,buy_date=datetime.now())

    db.session.add(buy)
    db.session.commit()
    return "Success"

BookChatBot/Bookbot/templates/author_info.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{{url_for('author.Authorinfo')}}" method="post" class="post-form my-3 ml-3">

            {{ form.csrf_token }}

            {{ form.title.label }}
            {{ form.title(class='form-control') }}
            <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if author_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 40%">제목</th>
                <th style="width: 40%">내용</th>
                <th style="width: 10%">작가</th>
                <th style="width: 20%">URL</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in author_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe }}</td>
             <td>{{ temp.description | safe | shortword }}</td>
             <td>{{ temp.author | safe | shortword }}</td>
              <td>
            <a href="{{ temp.link |safe }}" target="_blank" style="color:blue; text-decoration:none;outline:none">{{temp.link|safe}}</a></td>
         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

BookChatBot/Bookbot/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">

    <title>네이버 검색</title>
</head>
<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{url_for('main.Bookinfo') }}">도서검색</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.Bookinfo') }}">도서명 검색</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('author.Authorinfo') }}">저자명 검색</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('movie.Movieinfo') }}">영화 검색</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('movie.Rankinfo') }}">영화 순위</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{ url_for('shop.Iteminfo') }}">상품 최저가 검색</a>


        </ul>
    </div>
</nav>
{% block content %}

{% endblock %}

<script src ="{{ url_for('static',filename='jquery-3.5.1.min.js') }}" > </script>
<script src ="{{ url_for('static',filename='bootstrap.min.js') }}" > </script>


</body>
</html>

BookChatBot/Bookbot/templates/book_info.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{{url_for('main.Bookinfo')}}" method="post" class="post-form my-3 ml-3">

            {{ form.csrf_token }}

            {{ form.title.label }}
            {{ form.title(class='form-control') }}
            <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if book_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 40%">제목</th>
                <th style="width: 40%">내용</th>
                <th style="width: 10%">작가</th>
                <th style="width: 20%">URL</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in book_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe }}</td>
             <td>{{ temp.description | safe | shortword }}</td>
             <td>{{ temp.author | safe | shortword }}</td>
            <td>
            <a href="{{ temp.link |safe }}" target="_blank" style="color:blue; text-decoration:none;outline:none">{{temp.link|safe}}</a></td>
         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

BookChatBot/Bookbot/templates/item_buy.html
{% extends 'base.html' %}
{% block content %}

<div>제품명:{{title}}</div>
<div>가격 : {{lprice}}</div>
<div>주소: {{form.address}}</div>

<form action="{{url_for('shop.Success')}}" method="post" class="post-form my-3 ml-3">
            <input type="hidden" name="title" value={{title}}>
            <input type="hidden" name="price" value={{price}}>
            <input type="hidden" name="address" value={{form.address.data}}>

            <button type="submit" class="btn btn-primary my-2">구매하기</button>

</form>
{% endblock %}

BookChatBot/Bookbot/templates/item_info.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{{url_for('shop.Iteminfo')}}" method="post" class="post-form my-3 ml-3">

            {{ form.csrf_token }}

            {{ form.title.label }}
            {{ form.title(class='form-control') }}
            <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if item_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 10%">제품명</th>
                <th style="width: 20%">브랜드</th>
                <th style="width: 20%">최저가</th>
                <th style="width: 20%">최고가</th>
                <th style="width: 20%">제품 이미지</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in item_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe }}</td>
            <td>{{ temp.brand | safe}}</td>
            <td>{{temp.lprice |safe|shortword}}</td>
            <td>{{ temp.hprice | safe | shortword}}</td>
           <td> <img src="{{ temp.image }}"  height="100" width="100" alt="제품 이미지"></td>

            <td><form action="{{url_for('shop.Buy') }}" method="post" class="post-form my-3 ml-3">
                <input type="hidden" name="title" value={{temp.title}}>
                <input type="hidden" name="lprice" value={{temp.lprice}}>
                <button type="submit" class="btn btn-primary my-2">구매</button>
            </form></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

BookChatBot/Bookbot/templates/movie_info.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{{url_for('movie.Movieinfo')}}" method="post" class="post-form my-3 ml-3">

            {{ form.csrf_token }}

            {{ form.title.label }}
            {{ form.title(class='form-control') }}
            <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if movie_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th style="width: 10%">번호</th>
                <th style="width: 10%">제목</th>
                <th style="width: 20%">개봉 날짜</th>
                <th style="width: 20%">출연진</th>
                <th style="width: 20%">평점</th>
                <th style="width: 20%">영화</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in movie_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp.title | safe }}</td>
            <td>{{ temp.pubDate | safe | datetime }}</td>
            <td>{{temp.actor|safe }}</td>
            <td>{{ temp.userRating | safe }}</td>
           <td> <img src="{{ temp.image }}" alt="My Image"></td>

         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

BookChatBot/Bookbot/templates/rank_info.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form action="{{url_for('movie.Rankinfo')}}" method="post" class="post-form my-3 ml-3">
            <input type="date" id="currentDate" name="keyword" value="{{keyword}}">
            <button type="submit" class="btn btn-primary my-2">검색</button>
    </form>
</div>
{% if rank_info_list %}
<div class="container my-3">
    <table class="table table-hover " style="font-size: 12px" >
        <thead>
            <tr class="text-center thead-dark">
                <th>rank</th>
                <th>title</th>
            </tr>
        </thead>
        <tbody>
        {% for temp in rank_info_list %}
        <tr class="text-center">
             <td>{{ loop.index }}</td>
             <td>{{ temp['title']}}</td>

         </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}